blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/eorzea-weather/eorzea-weather/discussions/new?category=ideas
    about: Suggest an idea for this project
